/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suppermarket;

import Component.Supplier_Report;
import java.awt.Image;
import javax.swing.UIManager;
import Component.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author asha
 */
public class suppermarket_Class extends javax.swing.JFrame {
     company com;
      panel_image pi;
     Image        image ;
  
      Company_Panel panel;
      Purchase_Panel purch_panel;
      Customer_Panel custo;
      Supplier supl;
      Purchases_panel pur;
      Sales_Trasaction_Panel  saleTra;
      Category  categ;
      Email_Panel email;
      Report_Montyly_Sales  month_sale;
      Report_Day_Sales day_rep_sale;
      int timerun=0;
      String day_night;
      String day_week;
      Menu_Panel menu;
      Daay_Purchase_Report day_purchase;
      Monthly_Purchase_Report month_purchase;
      Stock_panel  stock;
      Sale_Amont_Balance_Report_panel  sale_amount;
     Supplier_Report suppl_report;
    public suppermarket_Class() {
        initComponents();
         setLocation(20,40);
         image();
        panel=new Company_Panel();
        purch_panel=new Purchase_Panel();
        custo=new Customer_Panel();
        supl=new Supplier();
        categ=new Category();
        pur=new Purchases_panel();
        saleTra=new Sales_Trasaction_Panel();
        month_sale=new Report_Montyly_Sales();
        day_rep_sale=new Report_Day_Sales();
        menu=new Menu_Panel();
        email=new Email_Panel();
        day_purchase=new Daay_Purchase_Report();
        month_purchase=new Monthly_Purchase_Report();
        stock=new Stock_panel ();
        sale_amount=new Sale_Amont_Balance_Report_panel();
        suppl_report=new Supplier_Report();
       ClockShow();
    }
    public void ClockShow(){
    new Thread(){
    public void run(){
    while(timerun==0){
    Calendar cal=new GregorianCalendar();
    int hour=cal.get(Calendar.HOUR);
    int minute=cal.get(Calendar.MINUTE);
    int second=cal.get(Calendar.SECOND);
     int AM_PM=cal.get(Calendar.AM_PM);
     int date=cal.get(Calendar.DATE);
     int month=cal.get(Calendar.MONTH);
     int year=cal.get(Calendar.YEAR);
     int day=cal.get(Calendar.DAY_OF_WEEK);
     day=day+1;
     if(day==1){
     day_week="Saturday";
     }else if(day==2){
       day_week="Sunday";
     }else if(day==3){
       day_week="Monday";
     }else if(day==4){
       day_week="Tuesday";
     }else if(day==5){
       day_week="Wednayday";
     }else if(day==6){
       day_week="Thursday";
     }else if(day==7){
       day_week="Friday";
     }
     if(AM_PM==1){
      day_night = "PM";
     }else {
     
     day_night = "AM";
     }
     if(cal.get(Calendar.HOUR)==0){
       hour=cal.get(Calendar.HOUR)+12;
     }
      if(cal.get(Calendar.MINUTE)==0){
       minute=Integer.parseInt("00");
     }
     String time= hour + ":" + minute + ":" + second +" "+ day_night;
     Clock_label.setText(time);
      String dat="Today  "+day_week +" , "+ date + "-" + month+1 + "-" + year ;
     date_label.setText(dat);
    }
    
    }
    }.start();
    
    }
    public void DateShow(){
    Calendar cal=new GregorianCalendar();
  
    }
    public void image(){
        {
            try
            {
             image = javax.imageio.ImageIO.read(new java.net.URL(getClass().getResource("Coin-icon.png"), "Coin-icon.png"));
            }
            catch (Exception e) { /*handled in paintComponent()*/ }
        
        }
           setIconImage(
                 image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        center_panel = new javax.swing.JPanel();
        center_image_label = new javax.swing.JLabel();
        Clock_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        m1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        company_jitem = new javax.swing.JMenuItem();
        Supplier_item = new javax.swing.JMenuItem();
        customer_menu = new javax.swing.JMenuItem();
        Category_item = new javax.swing.JMenuItem();
        menu_ = new javax.swing.JMenuItem();
        m2 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        m3 = new javax.swing.JMenu();
        Register_purchase = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        m4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        m5 = new javax.swing.JMenu();
        sales_Transa_Item = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        m6 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        day_sale_report_item = new javax.swing.JMenuItem();
        Month_sale_report = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        day_purcahes_item_ = new javax.swing.JMenuItem();
        Month_purchase_item_ = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        stock_item = new javax.swing.JMenuItem();
        sale_balance = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        supplier_report_item = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        m7 = new javax.swing.JMenu();
        m8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText(" TELNET RESTAURANT SOFTWARE");

        jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Mail-icon.png"))); // NOI18N
        jLabel2.setToolTipText("Email icon");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel2);

        jSeparator2.setPreferredSize(new java.awt.Dimension(100, 0));
        jToolBar1.add(jSeparator2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/SMS-Message-icon.png"))); // NOI18N
        jLabel4.setToolTipText("Sms");
        jToolBar1.add(jLabel4);

        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 0));
        jToolBar1.add(jSeparator4);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Money-icon2.png"))); // NOI18N
        jLabel3.setToolTipText("Profit");
        jToolBar1.add(jLabel3);

        center_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Center Panel"));

        center_image_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Capture3.PNG"))); // NOI18N
        center_image_label.setText("jLabel6");

        javax.swing.GroupLayout center_panelLayout = new javax.swing.GroupLayout(center_panel);
        center_panel.setLayout(center_panelLayout);
        center_panelLayout.setHorizontalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(center_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(center_image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        center_panelLayout.setVerticalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, center_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(center_image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 453, Short.MAX_VALUE))
        );

        Clock_label.setBackground(new java.awt.Color(0, 0, 0));
        Clock_label.setFont(new java.awt.Font("DS-Digital", 1, 36)); // NOI18N
        Clock_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        date_label.setFont(new java.awt.Font("DS-Digital", 1, 24)); // NOI18N
        date_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(204, 0, 0));
        jMenuBar1.setFont(new java.awt.Font("Blackadder ITC", 1, 36)); // NOI18N

        m1.setText("Master");
        m1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        m1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        m1.add(jSeparator1);
        m1.add(jSeparator3);

        company_jitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        company_jitem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        company_jitem.setForeground(new java.awt.Color(0, 0, 51));
        company_jitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Company-icon.png"))); // NOI18N
        company_jitem.setText("Company");
        company_jitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company_jitemActionPerformed(evt);
            }
        });
        m1.add(company_jitem);

        Supplier_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Supplier_item.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Supplier_item.setForeground(new java.awt.Color(0, 0, 51));
        Supplier_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/user-group-icon.png"))); // NOI18N
        Supplier_item.setText("Supplier");
        Supplier_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_itemActionPerformed(evt);
            }
        });
        m1.add(Supplier_item);

        customer_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        customer_menu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        customer_menu.setForeground(new java.awt.Color(0, 0, 51));
        customer_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/User-Group-icon_1.png"))); // NOI18N
        customer_menu.setText("Customer");
        customer_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_menuActionPerformed(evt);
            }
        });
        m1.add(customer_menu);

        Category_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        Category_item.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Category_item.setForeground(new java.awt.Color(0, 0, 51));
        Category_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/category-group-icon.png"))); // NOI18N
        Category_item.setText("Category");
        Category_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_itemActionPerformed(evt);
            }
        });
        m1.add(Category_item);

        menu_.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        menu_.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menu_.setForeground(new java.awt.Color(0, 0, 51));
        menu_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/income-icon.png"))); // NOI18N
        menu_.setText("Menu");
        menu_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ActionPerformed(evt);
            }
        });
        m1.add(menu_);

        jMenuBar1.add(m1);

        m2.setText("Account");
        m2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(0, 0, 51));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Admin-icon.png"))); // NOI18N
        jMenuItem13.setText("Administrator");
        m2.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(0, 0, 51));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/User-Files-icon.png"))); // NOI18N
        jMenuItem14.setText("User");
        m2.add(jMenuItem14);

        jMenuBar1.add(m2);

        m3.setText("Purchase");
        m3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Register_purchase.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        Register_purchase.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Register_purchase.setForeground(new java.awt.Color(0, 0, 51));
        Register_purchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/cash-register-icon3.png"))); // NOI18N
        Register_purchase.setText("Register Product");
        Register_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_purchaseActionPerformed(evt);
            }
        });
        m3.add(Register_purchase);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 0, 51));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/History-Folder-Sakura-icon.png"))); // NOI18N
        jMenuItem2.setText("History");
        m3.add(jMenuItem2);

        jMenuBar1.add(m3);

        m4.setText("Sales");
        m4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(0, 0, 51));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/cash-register-2-icon.png"))); // NOI18N
        jMenuItem4.setText("Register Sales");
        m4.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 0, 51));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/History-Folder-Blue-icon.png"))); // NOI18N
        jMenuItem5.setText("History");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        m4.add(jMenuItem5);

        jMenuBar1.add(m4);

        m5.setBackground(new java.awt.Color(51, 51, 51));
        m5.setText("Transaction");
        m5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        sales_Transa_Item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sales_Transa_Item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/sale-icon.png"))); // NOI18N
        sales_Transa_Item.setText("Sales");
        sales_Transa_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_Transa_ItemActionPerformed(evt);
            }
        });
        m5.add(sales_Transa_Item);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/purchase-icon.png"))); // NOI18N
        jMenuItem7.setText("Purchase");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        m5.add(jMenuItem7);

        jMenuItem27.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/money-icon.png"))); // NOI18N
        jMenuItem27.setText("Expenses");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        m5.add(jMenuItem27);

        jMenuBar1.add(m5);

        m6.setText("Report");
        m6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/sales-report-icon2.png"))); // NOI18N
        jMenu10.setText("Sales");

        day_sale_report_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        day_sale_report_item.setText("Day Sale");
        day_sale_report_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day_sale_report_itemActionPerformed(evt);
            }
        });
        jMenu10.add(day_sale_report_item);

        Month_sale_report.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        Month_sale_report.setText("Monthly Sales");
        Month_sale_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Month_sale_reportActionPerformed(evt);
            }
        });
        jMenu10.add(Month_sale_report);

        m6.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/reports-icon.png"))); // NOI18N
        jMenu11.setText("Purchase");

        day_purcahes_item_.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        day_purcahes_item_.setText("Day Purchase");
        day_purcahes_item_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day_purcahes_item_ActionPerformed(evt);
            }
        });
        jMenu11.add(day_purcahes_item_);

        Month_purchase_item_.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        Month_purchase_item_.setText("Monthly Purchase");
        Month_purchase_item_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Month_purchase_item_ActionPerformed(evt);
            }
        });
        jMenu11.add(Month_purchase_item_);

        m6.add(jMenu11);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Product-sale-report-icon.png"))); // NOI18N
        jMenuItem16.setText("Product Sale Report");
        m6.add(jMenuItem16);

        stock_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        stock_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/report-icon.png"))); // NOI18N
        stock_item.setText("Stock Report");
        stock_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_itemActionPerformed(evt);
            }
        });
        m6.add(stock_item);

        sale_balance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        sale_balance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/reports-icon2.png"))); // NOI18N
        sale_balance.setText("Sale Amount Balance Report");
        sale_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale_balanceActionPerformed(evt);
            }
        });
        m6.add(sale_balance);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/distributor-report-icon.png"))); // NOI18N
        jMenuItem19.setText("Expense Report");
        m6.add(jMenuItem19);

        supplier_report_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        supplier_report_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/document-scroll-icon.png"))); // NOI18N
        supplier_report_item.setText("Supplier Balance");
        supplier_report_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_report_itemActionPerformed(evt);
            }
        });
        m6.add(supplier_report_item);

        jMenuItem26.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/custom-reports-icon.png"))); // NOI18N
        jMenuItem26.setText("Price List");
        m6.add(jMenuItem26);

        jMenuBar1.add(m6);

        m7.setText("About");
        m7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuBar1.add(m7);

        m8.setText("Help");
        m8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuBar1.add(m8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(center_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clock_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clock_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(center_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Supplier_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_itemActionPerformed
        // TODO add your handling code here:
        supl.setBounds(20,120,970, 460);
         //center_panel.
                 remove(center_image_label);
    remove(suppl_report);
          remove(panel);
          remove(center_panel);
                remove(stock);
                  remove(saleTra);
                   remove(email);
                   remove(menu);
         remove(sale_amount);
                 remove(pur);
                 remove(day_purchase);
                 remove(categ);
                 remove(month_sale);
                    remove(month_purchase);
                 remove(custo);
         // center_panel.
                  add(supl);
        // center_panel.
                 validate();
         //center_panel.
                 repaint();
    }//GEN-LAST:event_Supplier_itemActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void Register_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_purchaseActionPerformed
        // TODO add your handling code here:
         purch_panel.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(center_panel);
         remove(panel);
         remove(pur);
         remove(supl);
           remove(suppl_report);
          remove(categ);
        remove(sale_amount);      
          remove(stock);
             remove(month_purchase);
          remove(day_purchase);
           remove(email);
          remove(menu);
          remove(saleTra);
         remove(month_sale);
        add(purch_panel);
         remove(custo);
         validate();
         repaint();
    }//GEN-LAST:event_Register_purchaseActionPerformed

    private void company_jitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company_jitemActionPerformed
       
        panel.setBounds(20,120,970, 490);
      
            remove(pur);
           remove(center_panel);
          remove(suppl_report);
                 remove(center_image_label);
            remove(sale_amount);
                 remove(purch_panel);
                 remove(stock);
                 remove(supl);
                  remove(categ);
                  remove(saleTra);
                  remove(day_purchase);
                  remove(month_sale);
                  remove(email);
                     remove(menu);
                 remove(custo);
                    remove(month_purchase);
                 add(panel);
        
                 validate();
         
         //center_panel.
                 repaint();
      
    }//GEN-LAST:event_company_jitemActionPerformed

    private void customer_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_menuActionPerformed
        // TODO add your handling code here:
         custo.setBounds(20,120,970, 490);
         remove(center_image_label);
      remove(purch_panel);
         remove(supl);
         remove(center_panel);
         remove(day_purchase);
         remove(panel);
          remove(email);
              remove(sale_amount);
          remove(menu);
          remove(categ);
         remove(month_sale);
          remove(saleTra);
            remove(suppl_report);
         remove(pur);
         remove(stock);
            remove(month_purchase);
        add(custo);
         validate();
         repaint();
      
    }//GEN-LAST:event_customer_menuActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
         pur.setBounds(20,120,970, 490);
         remove(center_image_label);
         remove(purch_panel);
        remove(supl);
         remove(center_panel);
         remove(day_purchase);
         remove(saleTra);
            remove(month_purchase);
          remove(categ);
              remove(sale_amount);
           remove(email);
          remove(menu);
            remove(suppl_report);
         remove(panel);
         remove(stock);
         remove(month_sale);
       add(pur);
         validate();
         repaint();
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void sales_Transa_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_Transa_ItemActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
         saleTra.setBounds(20,120,970, 490);
         remove(center_image_label);
         remove(purch_panel);
         remove(supl);
         remove(month_sale);
        remove(panel);
         remove(categ);
             remove(sale_amount);
         remove(day_purchase);
          remove(email);
             remove(month_purchase);
          remove(menu);
          remove(stock);
            remove(suppl_report);
        remove(pur);
        remove(center_panel);
         remove(day_rep_sale);
         add(saleTra);
         validate();
         repaint();
    }//GEN-LAST:event_sales_Transa_ItemActionPerformed

    private void day_sale_report_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day_sale_report_itemActionPerformed
        // TODO add your handling code here:
        day_rep_sale.setBounds(20,120,970, 490);
         remove(center_image_label);
         remove(purch_panel);
         remove(supl);
         remove(pur);
          remove(categ);
          remove(day_purchase);
           remove(email);
          remove(menu);
              remove(sale_amount);
             remove(month_purchase);
        remove(saleTra);
        remove(stock);
          remove(suppl_report);
        remove(center_panel);
         remove(panel);
         remove(month_sale);
        add(day_rep_sale);
        validate();
         repaint();
    }//GEN-LAST:event_day_sale_report_itemActionPerformed

    private void Month_sale_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Month_sale_reportActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
       month_sale.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
         remove(saleTra);
          remove(email);
          remove(menu);
         remove(center_panel);
         remove(day_purchase);
        remove(pur);
        remove(categ);
          remove(suppl_report);
         remove(sale_amount);
        remove(stock);
           remove(month_purchase);
        remove(panel);
         remove(day_rep_sale);
         add(month_sale);
        validate();
         repaint();
    }//GEN-LAST:event_Month_sale_reportActionPerformed

    private void Category_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_itemActionPerformed
        // TODO add your handling code here:
         categ.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
         remove(saleTra);
         remove(center_panel);
        remove(pur);
        remove(sale_amount);
         remove(email);
         remove(day_purchase);
          remove(menu);
             remove(month_purchase);
        remove(panel);
          remove(suppl_report);
        remove(stock);
         remove(day_rep_sale);
         add(categ);
        validate();
         repaint();
    }//GEN-LAST:event_Category_itemActionPerformed

    private void menu_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ActionPerformed
        // TODO add your handling code here:
        menu.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
         remove(saleTra);
         remove(center_panel);
        remove(pur);
         remove(email);
           remove(suppl_report);
        remove(sale_amount);
         remove(month_purchase);
        remove(day_purchase); 
        remove(panel);
        remove(stock);
         remove(day_rep_sale);
         add(menu);
        validate();
         repaint();
    }//GEN-LAST:event_menu_ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         email.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
          remove(menu);
           remove(day_purchase);
         remove(saleTra);
         remove(center_panel);
        remove(pur);
        remove(panel);
          remove(suppl_report);
        remove(sale_amount);
        remove(stock);
           remove(month_purchase);
         remove(day_rep_sale);
         add(email);
        validate();
         repaint();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void day_purcahes_item_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day_purcahes_item_ActionPerformed
        // TODO add your handling code here:
        day_purchase.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
          remove(menu);
         remove(saleTra);
            remove(month_purchase);
         remove(center_panel);
         remove(stock);
         remove(sale_amount);
        remove(pur);
          remove(suppl_report);
        remove(panel);
         remove(day_rep_sale);
         add(day_purchase);
        validate();
         repaint();
    }//GEN-LAST:event_day_purcahes_item_ActionPerformed

    private void Month_purchase_item_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Month_purchase_item_ActionPerformed
        // TODO add your handling code here:
        month_purchase.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
          remove(menu);
         remove(saleTra);
         remove(center_panel);
        remove(pur);
          remove(suppl_report);
        remove(panel);
        remove(sale_amount);
         remove(stock);
          remove(day_purchase);
         remove(day_rep_sale);
         add(month_purchase);
        validate();
         repaint();
    }//GEN-LAST:event_Month_purchase_item_ActionPerformed

    private void stock_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_itemActionPerformed
        // TODO add your handling code here:
        stock.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
          remove(menu);
         remove(saleTra);
         remove(center_panel);
        remove(pur);
          remove(suppl_report);
        remove(panel);
         remove(sale_amount);
         remove(month_purchase);
         remove(day_purchase);
         remove(day_rep_sale);
         add(stock);
        validate();
         repaint();
    }//GEN-LAST:event_stock_itemActionPerformed

    private void sale_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale_balanceActionPerformed
        // TODO add your handling code here:
        sale_amount.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
          remove(menu);
         remove(saleTra);
         remove(center_panel);
        remove(pur);
        remove(panel);
            remove(stock);
            remove(suppl_report);
         remove(month_purchase);
         remove(day_purchase);
         remove(day_rep_sale);
         add(sale_amount);
        validate();
         repaint();
    }//GEN-LAST:event_sale_balanceActionPerformed

    private void supplier_report_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_report_itemActionPerformed
        // TODO add your handling code here:
       suppl_report.setBounds(20,120,970, 490);
        remove(center_image_label);
        remove(purch_panel);
         remove(supl);
          remove(menu);
         remove(saleTra);
         remove(center_panel);
        remove(pur);
        remove(panel);
            remove(stock);
         remove(month_purchase);
         remove(day_purchase);
         remove(day_rep_sale);
         add(suppl_report);
        validate();
         repaint();
    }//GEN-LAST:event_supplier_report_itemActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
         //   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             //   if ("Nimbus".equals(info.getName())) {
                 //   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                 //   break;
              //UIManager.setLookAndFeel(" de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel");
                
               UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
               // }
           // }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suppermarket_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suppermarket_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suppermarket_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suppermarket_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suppermarket_Class().setVisible(true);
            }
        });
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Category_item;
    private javax.swing.JLabel Clock_label;
    private javax.swing.JMenuItem Month_purchase_item_;
    private javax.swing.JMenuItem Month_sale_report;
    private javax.swing.JMenuItem Register_purchase;
    private javax.swing.JMenuItem Supplier_item;
    private javax.swing.JLabel center_image_label;
    private javax.swing.JPanel center_panel;
    private javax.swing.JMenuItem company_jitem;
    private javax.swing.JMenuItem customer_menu;
    private javax.swing.JLabel date_label;
    private javax.swing.JMenuItem day_purcahes_item_;
    private javax.swing.JMenuItem day_sale_report_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu m1;
    private javax.swing.JMenu m2;
    private javax.swing.JMenu m3;
    private javax.swing.JMenu m4;
    private javax.swing.JMenu m5;
    private javax.swing.JMenu m6;
    private javax.swing.JMenu m7;
    private javax.swing.JMenu m8;
    private javax.swing.JMenuItem menu_;
    private javax.swing.JMenuItem sale_balance;
    private javax.swing.JMenuItem sales_Transa_Item;
    private javax.swing.JMenuItem stock_item;
    private javax.swing.JMenuItem supplier_report_item;
    // End of variables declaration//GEN-END:variables
}
