/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Component;

/**
 *
 * @author asha
 */
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.*;
import suppermarket.DatabaseConnection;
import net.proteanit.sql.DbUtils;
public class Company_Panel extends javax.swing.JPanel {

     Connection conn;
   Statement st;
   ResultSet rs;
    Statement st1;
   ResultSet rs1;
   DatabaseConnection db;
   int s=0;
   byte[]personal_image=null;
    String filename=null;
    Image image=null;
    /**
     * Creates new form Company_Panel
     */
    public Company_Panel() {
        initComponents();
        db=new DatabaseConnection();
        conn=db.ConnectDB();
    }
    
   
     private void Upadet_Table(){
    String query="select * from Company_Table ";
    try{
   st= conn.createStatement();
   rs=st.executeQuery(query);
   company_table.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(Exception b){
    
    }
    
    }
         public void Empty_TextField(){
     id_txt.setText("");
              name_txt.setText("");
              type_txt.setText("");
              address_txt.setText("");
              email_txt.setText("");
              tel_txt.setText("");
             mobile_txt.setText("");
              web_txt.setText("");
    
    }
    
  public boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
  private boolean isvalideMobileNumber(String mobile){
       String patern="^[+]\\d{3}-\\d{3}-\\d{6}$";
  
      java.util.regex.Pattern p = java.util.regex.Pattern.compile(patern);
       java.util.regex.Matcher m = p.matcher(mobile);
           return m.matches();
  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        company_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        type_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tel_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        web_txt = new javax.swing.JTextField();
        mobile_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        save_button = new javax.swing.JButton();
        view_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        browse_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Label = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("company datails"));

        company_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        company_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                company_tableMouseClicked(evt);
            }
        });
        company_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                company_tableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(company_table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Company Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Company Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Company Email");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Company Tele #");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Company Website");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Company Address");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Company Type");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Company Mobile");

        mobile_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_txtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Company ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(type_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(id_txt)
                    .addComponent(name_txt)
                    .addComponent(address_txt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mobile_txt)
                        .addComponent(tel_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(web_txt))
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(type_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(mobile_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(web_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Save-icon.png"))); // NOI18N
        save_button.setText("Save");
        save_button.setPreferredSize(new java.awt.Dimension(55, 28));
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        view_button.setText("View");
        view_button.setMaximumSize(new java.awt.Dimension(55, 28));
        view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_buttonActionPerformed(evt);
            }
        });

        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/edit-validated-icon.png"))); // NOI18N
        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Actions-edit-delete-icon.png"))); // NOI18N
        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        browse_button.setText("Browse");
        browse_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_buttonActionPerformed(evt);
            }
        });

        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\asha\\Documents\\NetBeansProjects\\SUPPERMARKET_SYSTEM\\src\\suppermarket\\Capture3.PNG")); // NOI18N
        Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Label.setMaximumSize(new java.awt.Dimension(180, 171));
        Label.setMinimumSize(new java.awt.Dimension(180, 171));
        Label.setPreferredSize(new java.awt.Dimension(180, 171));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(browse_button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browse_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(save_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mobile_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_txtActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
                if(id_txt.getText().length()==0 && name_txt.getText().length()==0
                &&type_txt.getText().length()==0 &&address_txt.getText().length()==0
                && email_txt.getText().length()==0 &&tel_txt.getText().length()==0
                && mobile_txt.getText().length()==0 &&web_txt.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Select data from table to update first","Update Information",JOptionPane.INFORMATION_MESSAGE);
        //Empty_TextField();
          return;
        }else{
        try{
        String query_update="update Company_Table set Company_ID='"+id_txt.getText()+"',"
                + "Company_Name='"+name_txt.getText()+"',Company_Type='"+type_txt.getText()+"',"
                + "Company_Address='"+address_txt.getText()+"',Company_Email='"+email_txt.getText()+"',"
                + "Company_Tele='"+tel_txt.getText()+"',Company_Mobile='"+mobile_txt.getText()+"',"
                + "Company_Website='"+web_txt.getText()+"' where Company_ID='"+id_txt.getText()+"'";
            st=conn.createStatement();
            st.executeUpdate(query_update);
              JOptionPane.showMessageDialog(null,"Data updated");
        }catch(Exception c){
          JOptionPane.showMessageDialog(null,"Data failed "+c);
        
        }
        Empty_TextField();
        Upadet_Table();
           }
    

     
    }//GEN-LAST:event_update_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
              if(id_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Company ID","ID Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        }else if(name_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Company Name","Name Empty",JOptionPane.ERROR_MESSAGE);
        Empty_TextField();
          return;
        
        }else if(type_txt.getText().length()==0){
        
       JOptionPane.showMessageDialog(null,"Fill Company Type","Type Empty",JOptionPane.ERROR_MESSAGE);
      //  Empty_TextField();
          return;
        }else if(address_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Company Address","Address Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        
        }else if(email_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Company Email","Email Empty",JOptionPane.ERROR_MESSAGE);
        //Empty_TextField();
       
        
        
        }else if(tel_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Company Tel Number","Tele Empty",JOptionPane.ERROR_MESSAGE);
        //Empty_TextField();
          return;
        
        
        }else if(mobile_txt.getText().length()==0){
        
        JOptionPane.showMessageDialog(null,"Fill Company Mobile","Mobile Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        }
        
        else{
             if(isValidEmailAddress(email_txt.getText())==false){
        JOptionPane.showMessageDialog(null,"invalide Email address","Email validate",JOptionPane.ERROR_MESSAGE);
        return;
        }else if(isvalideMobileNumber(mobile_txt.getText())== false){
         JOptionPane.showMessageDialog(null,"invalide  Mobile Number","Mobile validate",JOptionPane.ERROR_MESSAGE);
        return;
        
        }else
             
             
            
             {
          
        String sql="insert into Company_Table values('"+id_txt.getText()+"',"
                + "'"+name_txt.getText()+"','"+type_txt.getText()+"','"+address_txt.getText()+"',"
                + "'"+email_txt.getText()+"','"+tel_txt.getText()+"','"+mobile_txt.getText()+"','"+web_txt.getText()+"','"+personal_image+"')";
        try{
           st=conn.createStatement();
           int p=st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data saved");
        }catch(Exception j){
            JOptionPane.showMessageDialog(null,"failed  saved  "+j);
    }
        
        Empty_TextField();
        Upadet_Table();
        }
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_buttonActionPerformed
        // TODO add your handling code here:
        Upadet_Table();
    }//GEN-LAST:event_view_buttonActionPerformed

    private void company_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_company_tableMouseClicked
        // TODO add your handling code here:
         try{
            int row=company_table.getSelectedRow();
        String Table_Clicked=(company_table.getModel().getValueAt(row, 0).toString());
         String query="select * from Company_Table where Company_ID='"+Table_Clicked+"'";
            st= conn.createStatement();
             rs=st.executeQuery(query);
             if(rs.next()){
             id_txt.setText(rs.getString("Company_ID"));
              name_txt.setText(rs.getString("Company_Name"));
              type_txt.setText(rs.getString("Company_Type"));
              address_txt.setText(rs.getString("Company_Address"));
              email_txt.setText(rs.getString("Company_Email"));
              tel_txt.setText(rs.getString("Company_Tele"));
             mobile_txt.setText(rs.getString("Company_Mobile"));
              web_txt.setText(rs.getString("Company_Website"));
               //id_txt.setText(rs.getString("Company_Logo"));
             
             }
        }catch(Exception v){
        
        }
    }//GEN-LAST:event_company_tableMouseClicked

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
           
        if(id_txt.getText().length()==0 && name_txt.getText().length()==0
                &&type_txt.getText().length()==0 &&address_txt.getText().length()==0
                && email_txt.getText().length()==0 &&tel_txt.getText().length()==0
                && mobile_txt.getText().length()==0 &&web_txt.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Select data from table to delte first","delete Information",JOptionPane.INFORMATION_MESSAGE);
        //Empty_TextField();
          return;
        }else{
        int p=JOptionPane.showConfirmDialog(null, "Do your really want to delete these data","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql="delete from Company_Table where Company_ID='"+id_txt.getText()+"'";
        try{
           st=conn.createStatement();
           st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data deleted");
        }catch(Exception j){
            JOptionPane.showMessageDialog(null,"failed deleted "+j);
    }
     Empty_TextField();  
     Upadet_Table();
        }
    }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void company_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_company_tableKeyPressed
        // TODO add your handling code here:
           if(evt.getKeyCode()== KeyEvent.VK_DOWN ||evt.getKeyCode()==KeyEvent.VK_UP ){
        
          try{
            int row=company_table.getSelectedRow();
        String Table_Clicked=(company_table.getModel().getValueAt(row, 0).toString());
         String query="select * from Company_Table where Company_ID='"+Table_Clicked+"'";
            st= conn.createStatement();
             rs=st.executeQuery(query);
             if(rs.next()){
             id_txt.setText(rs.getString("Company_ID"));
              name_txt.setText(rs.getString("Company_Name"));
              type_txt.setText(rs.getString("Company_Type"));
              address_txt.setText(rs.getString("Company_Address"));
              email_txt.setText(rs.getString("Company_Email"));
              tel_txt.setText(rs.getString("Company_Tele"));
             mobile_txt.setText(rs.getString("Company_Mobile"));
              web_txt.setText(rs.getString("Company_Website"));
               //id_txt.setText(rs.getString("Company_Logo"));
             
             }
        }catch(Exception v){
        
        
        }
        
        }
    }//GEN-LAST:event_company_tableKeyPressed

    private void browse_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_buttonActionPerformed
    // Label.setIcon(new javax.swing.ImageIcon("Coin-icon.png"));
 //Label.validate();
 //Label.repaint();
        
        try{
        JFileChooser choose=new JFileChooser();
        choose.setDialogTitle ("Choose Image..");
        
      choose.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
       int value= choose.showOpenDialog(null);
       if(value==JFileChooser.APPROVE_OPTION){
        File file=choose.getSelectedFile();
         filename=file.getAbsolutePath();
         ImageIcon icon=new ImageIcon(filename);
         Label.setIcon(icon);
        
       }else if(value==JFileChooser.CANCEL_OPTION){
           Label.setText("No file selected");
       } 
       
           
           

            File fl=new File(filename);
            FileInputStream fis=new FileInputStream(fl);
            ByteArrayOutputStream bos=new   ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readNum ;(readNum=fis.read(buf))!=-1;){
                bos.write(buf, 0, readNum);

            }
            personal_image=bos.toByteArray();
        }catch(Exception k){
            System.out.println(k);

        }
    }//GEN-LAST:event_browse_buttonActionPerformed

     public ImageIcon ResizeImage(String ImagePath) {
         ImageIcon MyImage = new ImageIcon(ImagePath);
         Image img = MyImage.getImage(); 
         Image newImg = img.getScaledInstance( Label.getWidth(),  Label.getHeight(), Image.SCALE_DEFAULT);
         ImageIcon image = new ImageIcon(newImg);
         return image;
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JTextField address_txt;
    private javax.swing.JButton browse_button;
    private javax.swing.JTable company_table;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton save_button;
    private javax.swing.JTextField tel_txt;
    private javax.swing.JTextField type_txt;
    private javax.swing.JButton update_button;
    private javax.swing.JButton view_button;
    private javax.swing.JTextField web_txt;
    // End of variables declaration//GEN-END:variables
}
