/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Component;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import suppermarket.DatabaseConnection;

/**
 *
 * @author asha
 */
   
public class Customer_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Customer_Panel
     */
    Connection conn;
   Statement st;
   ResultSet rs;
    Statement st1;
   ResultSet rs1;
   DatabaseConnection db;
    order_form order;
    public Customer_Panel() {
        initComponents();
        order=new order_form();
        db=new DatabaseConnection();
        conn=db.ConnectDB();
    }
      private void Upadet_Table(){
    String query="select * from Customer_Table ";
    try{
   st= conn.createStatement();
   rs=st.executeQuery(query);
   customer_table.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(Exception b){
    
    }
    
    }
    
          public void Empty_TextField(){
     id_txt.setText("");
              name_txt.setText("");
              
              address_txt.setText("");
              email_txt.setText("");
              
             mobile_txt.setText("");
             
    
    }
    
  public boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
  private boolean isvalideMobileNumber(String mobile){
       String patern="^[+]\\d{3}-\\d{3}-\\d{6}$";
  
      java.util.regex.Pattern p = java.util.regex.Pattern.compile(patern);
       java.util.regex.Matcher m = p.matcher(mobile);
           return m.matches();
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        save_customer_button = new javax.swing.JButton();
        mobile_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        view_cust = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        delete_cust = new javax.swing.JButton();
        update_cust = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        claer_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_txt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        customer_table = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer > Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer > Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 51)))); // NOI18N

        save_customer_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        save_customer_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Save-icon.png"))); // NOI18N
        save_customer_button.setText("Save");
        save_customer_button.setPreferredSize(new java.awt.Dimension(120, 25));
        save_customer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_customer_buttonActionPerformed(evt);
            }
        });

        mobile_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cust Address");

        email_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        id_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cust ID");

        view_cust.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        view_cust.setText("View");
        view_cust.setPreferredSize(new java.awt.Dimension(120, 25));
        view_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_custActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Cust Email");

        name_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cust Mobile");

        delete_cust.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        delete_cust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Actions-edit-delete-icon.png"))); // NOI18N
        delete_cust.setText("Delete");
        delete_cust.setPreferredSize(new java.awt.Dimension(120, 25));
        delete_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_custActionPerformed(evt);
            }
        });

        update_cust.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        update_cust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/edit-validated-icon.png"))); // NOI18N
        update_cust.setText("Update");
        update_cust.setPreferredSize(new java.awt.Dimension(120, 25));
        update_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_custActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cust Name");

        claer_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        claer_button.setText("Clear");
        claer_button.setPreferredSize(new java.awt.Dimension(120, 25));
        claer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claer_buttonActionPerformed(evt);
            }
        });

        address_txt.setColumns(20);
        address_txt.setRows(5);
        jScrollPane1.setViewportView(address_txt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save_customer_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_cust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete_cust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_cust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(52, 52, 52))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(id_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mobile_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(claer_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_cust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_customer_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_cust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_cust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(claer_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customer_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_tableMouseClicked(evt);
            }
        });
        customer_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customer_tableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(customer_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void claer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claer_buttonActionPerformed
        // TODO add your handling code here:
        //order.setVisible(true);
        Empty_TextField();
    }//GEN-LAST:event_claer_buttonActionPerformed

    private void delete_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_custActionPerformed
        // TODO add your handling code here:
                 if(id_txt.getText().length()==0 && name_txt.getText().length()==0
                 &&address_txt.getText().length()==0 && email_txt.getText().length()==0 
                && mobile_txt.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Select data from table to update first","Update Information",JOptionPane.INFORMATION_MESSAGE);
        //Empty_TextField();
          return;
        }else{
         int p=JOptionPane.showConfirmDialog(null, "Do your really want to delete these data","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
           String sql="delete from Customer_Table where Customer_ID='"+id_txt.getText()+"'";
        try{
           st=conn.createStatement();
           st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data deleted");
        }catch(Exception j){
            JOptionPane.showMessageDialog(null,"failed deleted "+j);
    }
     Empty_TextField();  
     Upadet_Table();
        }
                 }
    }//GEN-LAST:event_delete_custActionPerformed

    private void save_customer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_customer_buttonActionPerformed
        // TODO add your handling code here:
                    if(id_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Customer ID","ID Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        }else if(name_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Customer Name","Name Empty",JOptionPane.ERROR_MESSAGE);
        
          return;
        
    
        }else if(address_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Cutomer Address","Address Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        
        }else if(email_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Customer Email","Email Empty",JOptionPane.ERROR_MESSAGE);
        //Empty_TextField();
       
        }
        
       else if(mobile_txt.getText().length()==0){
        
        JOptionPane.showMessageDialog(null,"Fill Customer Mobile","Mobile Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        }
        
        else{
             if(isValidEmailAddress(email_txt.getText())==false){
        JOptionPane.showMessageDialog(null,"invalide Email address","Email validate",JOptionPane.ERROR_MESSAGE);
        return;
        }else if(isvalideMobileNumber(mobile_txt.getText())== false){
         JOptionPane.showMessageDialog(null,"invalide  Mobile Number","Mobile validate",JOptionPane.ERROR_MESSAGE);
        return;
        
        }else
             
             
            
             {
          
        String sql="insert into Customer_Table values('"+id_txt.getText()+"',"
                + "'"+name_txt.getText()+"','"+address_txt.getText()+"',"
                + "'"+mobile_txt.getText()+"','"+email_txt.getText()+"')";
        try{
           st=conn.createStatement();
           int p=st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data saved");
        }catch(Exception j){
            JOptionPane.showMessageDialog(null,"failed  saved  "+j);
    }
        
        Empty_TextField();
        Upadet_Table();
        }
        }
    }//GEN-LAST:event_save_customer_buttonActionPerformed

    private void update_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_custActionPerformed
        // TODO add your handling code here:
                 if(id_txt.getText().length()==0 && name_txt.getText().length()==0
                 &&address_txt.getText().length()==0 && email_txt.getText().length()==0 
                && mobile_txt.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Select data from table to update first","Update Information",JOptionPane.INFORMATION_MESSAGE);
        //Empty_TextField();
          return;
        }else{
                 if(isValidEmailAddress(email_txt.getText())==false){
        JOptionPane.showMessageDialog(null,"invalide Email address","Email validate",JOptionPane.ERROR_MESSAGE);
        return;
        }else if(isvalideMobileNumber(mobile_txt.getText())== false){
         JOptionPane.showMessageDialog(null,"invalide  Mobile Number","Mobile validate",JOptionPane.ERROR_MESSAGE);
        return;
        
        }else
             
             
            
             {        
                     
        try{
        String query_update="update Customer_Table set Customer_ID='"+id_txt.getText()+"',"
                + "Customer_Name='"+name_txt.getText()+"',"
                + "Customer_Address='"+address_txt.getText()+"',"
                + "Customer_Mobile='"+mobile_txt.getText()+"',"
                + "Customer_Email='"+email_txt.getText()+"' where Customer_ID='"+id_txt.getText()+"'";
            st=conn.createStatement();
            st.executeUpdate(query_update);
              JOptionPane.showMessageDialog(null,"Data updated");
        }catch(Exception c){
          JOptionPane.showMessageDialog(null,"Data failed "+c);
        
        }
        Empty_TextField();
        Upadet_Table();
           }
                 }
    }//GEN-LAST:event_update_custActionPerformed

    private void view_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_custActionPerformed
        // TODO add your handling code here:
          Upadet_Table();
    }//GEN-LAST:event_view_custActionPerformed

    private void customer_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_tableMouseClicked
        // TODO add your handling code here:
           try{
            int row=customer_table.getSelectedRow();
        String Table_Clicked=(customer_table.getModel().getValueAt(row, 0).toString());
         String query="select * from Customer_Table where Customer_ID='"+Table_Clicked+"'";
            st= conn.createStatement();
             rs=st.executeQuery(query);
             if(rs.next()){
             id_txt.setText(rs.getString("Customer_ID"));
              name_txt.setText(rs.getString("Customer_Name"));
              
              address_txt.setText(rs.getString("Customer_Address"));
              
              
             mobile_txt.setText(rs.getString("Customer_Mobile"));
            email_txt.setText(rs.getString("Customer_Email"));
               
             
             }
        }catch(Exception v){
        
        }
    }//GEN-LAST:event_customer_tableMouseClicked

    private void customer_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customer_tableKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()== KeyEvent.VK_DOWN ||evt.getKeyCode()==KeyEvent.VK_UP ){
        
          try{
            int row=customer_table.getSelectedRow();
        String Table_Clicked=(customer_table.getModel().getValueAt(row, 0).toString());
         String query="select * from Customer_Table where Customer_ID='"+Table_Clicked+"'";
            st= conn.createStatement();
             rs=st.executeQuery(query);
             if(rs.next()){
             id_txt.setText(rs.getString("Customer_ID"));
              name_txt.setText(rs.getString("Customer_Name"));
             
              address_txt.setText(rs.getString("Customer_Address"));
              mobile_txt.setText(rs.getString("Customer_Mobile"));
              email_txt.setText(rs.getString("Customer_Email"));
             
               //id_txt.setText(rs.getString("Company_Logo"));
             
             }
        }catch(Exception v){
        
        
        }
        
        }
    }//GEN-LAST:event_customer_tableKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address_txt;
    private javax.swing.JButton claer_button;
    private javax.swing.JTable customer_table;
    private javax.swing.JButton delete_cust;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton save_customer_button;
    private javax.swing.JButton update_cust;
    private javax.swing.JButton view_cust;
    // End of variables declaration//GEN-END:variables
}
