/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Component;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import suppermarket.DatabaseConnection;

/**
 *
 * @author asha
 */
public class Purchase_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Purchase_Panel
     */
        Connection conn;
   Statement st;
   ResultSet rs;
    Statement st1;
   ResultSet rs1;
   DatabaseConnection db;
    java.util.Date dt1;
    double coste;
    double earne;
    public Purchase_Panel() {
        initComponents();
          db=new DatabaseConnection();
        conn=db.ConnectDB();
        Filecombo();
        Filecombo2();
    }
    
    
     private void Filecombo(){
    String query="select * from Category_Table ";
    try{
   st= conn.createStatement();
   rs=st.executeQuery(query);
   while(rs.next()){
   String category=rs.getString("Category_Name");
   category_combo.addItem(category);
   
   }
    
    }catch(Exception b){
    
    }
    
    }
     private void Filecombo2(){
    String query="select * from Supplier_Table ";
    try{
   st= conn.createStatement();
   rs=st.executeQuery(query);
   while(rs.next()){
   String category=rs.getString("Supplier_Name");
   supplier_combo.addItem(category);
   
   }
    
    }catch(Exception b){
    
    }
    
    }
     
     
     private void Cost(){
       String query="select SUM(Purchase_Price) as Cost from Purchased_Registration ";
    try{
   st= conn.createStatement();
   rs=st.executeQuery(query);
    if(rs.next()){
      coste= rs.getDouble("Cost");
    purcahse_cost.setText(""+coste);
   
    }
    
    }catch(Exception b){
    
    }
    
     
     
     }
      private void Earn(){
       String query="select SUM(Selling_Price) as Earn from Purchased_Registration ";
    try{
   st= conn.createStatement();
   rs=st.executeQuery(query);
    if(rs.next()){
      earne= rs.getDouble("Earn");
  earn_after_selling.setText(""+earne);
   
    }
    
    }catch(Exception b){
    
    }
    
     
     
     }
     
        private void Upadet_Table(){
    String query="select * from Purchased_Registration ";
    try{
   st= conn.createStatement();
   rs=st.executeQuery(query);
   entry_purchase_table.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(Exception b){
    
    }
    
    }
           public void Empty_TextField(){
               String st=new String(" ");
               id_txt.setText("");
              name_txt.setText("");
             selling_txt.setText("");
             date_txt.equals(st);
              purchase_txt.setText("");
             vat_txt.setText("");
              discount_txt.setText("");
             quantity_txt.setText("");
              //web_txt.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entry_purchase_table = new javax.swing.JTable();
        save_purchase_ = new javax.swing.JButton();
        update_purchase_ = new javax.swing.JButton();
        delete_purchase_ = new javax.swing.JButton();
        view_purchase_ = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        id_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selling_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        supplier_combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        discount_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantity_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        category_combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        vat_txt = new javax.swing.JTextField();
        purchase_txt = new javax.swing.JTextField();
        date_txt = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        earn_after_selling = new javax.swing.JTextField();
        balance_after_Paying = new javax.swing.JTextField();
        profit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        amount_given_topurchase = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        purcahse_cost = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchase> Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        entry_purchase_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        entry_purchase_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entry_purchase_tableMouseClicked(evt);
            }
        });
        entry_purchase_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entry_purchase_tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(entry_purchase_table);

        save_purchase_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Save-icon.png"))); // NOI18N
        save_purchase_.setText("Save");
        save_purchase_.setPreferredSize(new java.awt.Dimension(120, 25));
        save_purchase_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_purchase_ActionPerformed(evt);
            }
        });

        update_purchase_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/edit-validated-icon.png"))); // NOI18N
        update_purchase_.setText("Update");
        update_purchase_.setPreferredSize(new java.awt.Dimension(120, 25));
        update_purchase_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_purchase_ActionPerformed(evt);
            }
        });

        delete_purchase_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Actions-edit-delete-icon.png"))); // NOI18N
        delete_purchase_.setText("Delete");
        delete_purchase_.setPreferredSize(new java.awt.Dimension(120, 25));
        delete_purchase_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_purchase_ActionPerformed(evt);
            }
        });

        view_purchase_.setText("View");
        view_purchase_.setPreferredSize(new java.awt.Dimension(120, 25));
        view_purchase_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_purchase_ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        id_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Product Name");

        selling_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Product_Barcode");

        supplier_combo.setPreferredSize(new java.awt.Dimension(28, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Vat (%)");

        name_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Purchase_Price");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Supplier Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Selling Price");

        discount_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Product Category");

        quantity_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Date");

        category_combo.setPreferredSize(new java.awt.Dimension(28, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Discount ( %)");

        vat_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        purchase_txt.setPreferredSize(new java.awt.Dimension(100, 25));

        date_txt.setDateFormatString("d- MMM- yyyy");
        date_txt.setPreferredSize(new java.awt.Dimension(91, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(category_combo, 0, 161, Short.MAX_VALUE)
                    .addComponent(name_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selling_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(discount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vat_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(purchase_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(supplier_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(purchase_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(vat_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(selling_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(discount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplier_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        earn_after_selling.setPreferredSize(new java.awt.Dimension(6, 25));

        balance_after_Paying.setPreferredSize(new java.awt.Dimension(6, 25));
        balance_after_Paying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balance_after_PayingMouseClicked(evt);
            }
        });
        balance_after_Paying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balance_after_PayingActionPerformed(evt);
            }
        });

        profit.setPreferredSize(new java.awt.Dimension(6, 25));
        profit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profitMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Cost");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Profit On Sell");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Balance");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Earn");

        amount_given_topurchase.setPreferredSize(new java.awt.Dimension(6, 25));
        amount_given_topurchase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amount_given_topurchaseKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Given Amount");

        purcahse_cost.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purcahse_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balance_after_Paying, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_given_topurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(earn_after_selling, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(purcahse_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amount_given_topurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balance_after_Paying, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(earn_after_selling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(view_purchase_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(save_purchase_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update_purchase_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete_purchase_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_purchase_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_purchase_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_purchase_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_purchase_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void balance_after_PayingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balance_after_PayingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balance_after_PayingActionPerformed

    private void view_purchase_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_purchase_ActionPerformed
        // TODO add your handling code here:
        Upadet_Table();
        Cost();
         Earn();
    }//GEN-LAST:event_view_purchase_ActionPerformed

    private void save_purchase_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_purchase_ActionPerformed
        // TODO add your handling code here:
         if(id_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Product Barcode","ID Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        }else if(name_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Product Name","Name Empty",JOptionPane.ERROR_MESSAGE);
      
          return;
        
        }else if(selling_txt.getText().length()==0){
        
       JOptionPane.showMessageDialog(null,"Fill Register selling price","Type Empty",JOptionPane.ERROR_MESSAGE);
      //  Empty_TextField();
          return;
        }else if(date_txt.getDate().equals(" ")){
        JOptionPane.showMessageDialog(null,"Fill Date","Address Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        
        }else if(purchase_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Purchase price","Email Empty",JOptionPane.ERROR_MESSAGE);
        //Empty_TextField();
       
        
        
        }else if(vat_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Vat","Tele Empty",JOptionPane.ERROR_MESSAGE);
        //Empty_TextField();
          return;
        
        
        }else if(discount_txt.getText().length()==0){
        
        JOptionPane.showMessageDialog(null,"Fill Discount","Mobile Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        }else if(quantity_txt.getText().length()==0){
        
        JOptionPane.showMessageDialog(null,"Fill Quanttity","Mobile Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        }
        
        else{
       SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyy");
         dt1=date_txt.getDate();
            java.sql.Date date = new java.sql.Date(date_txt.getDate().getTime());
          
        String sql="insert into Purchased_Registration  values('"+id_txt.getText()+"','"+name_txt.getText()+"','"+(String)category_combo.getSelectedItem()+"','"+purchase_txt.getText()+"','"+vat_txt.getText()+"','"+discount_txt.getText()+"','"+selling_txt.getText()+"','"+(String)supplier_combo.getSelectedItem()+"','"+quantity_txt.getText()+"','"+date+"')";
        try{
           st=conn.createStatement();
           int p=st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data saved");
        }catch(Exception j){
            JOptionPane.showMessageDialog(null,"failed  saved  "+j);
    }
        
       // Empty_TextField();
        Upadet_Table();
         Cost();
         Earn();
        } 
    }//GEN-LAST:event_save_purchase_ActionPerformed

    private void amount_given_topurchaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amount_given_topurchaseKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_amount_given_topurchaseKeyTyped

    private void balance_after_PayingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balance_after_PayingMouseClicked
        // TODO add your handling code here:
         double amount;
        double amount2,balance;
         amount=Double.parseDouble(amount_given_topurchase.getText());
        
          amount2=Double.parseDouble( purcahse_cost.getText());
         balance= amount-amount2;
         balance_after_Paying.setText(""+balance);
    }//GEN-LAST:event_balance_after_PayingMouseClicked

    private void delete_purchase_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_purchase_ActionPerformed
        // TODO add your handling code here:
               
        if(id_txt.getText().length()==0 && name_txt.getText().length()==0
               &&selling_txt.getText().length()==0
                && date_txt.getDate().equals("") &&purchase_txt.getText().length()==0
                &&vat_txt.getText().length()==0 &&discount_txt.getText().length()==0
                &&quantity_txt.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Select data from table to delte first","delete Information",JOptionPane.INFORMATION_MESSAGE);
        //Empty_TextField();"
          return;
        }else{
        int p=JOptionPane.showConfirmDialog(null, "Do your really want to delete these data","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql="delete from Purchased_Registration  where Product_Barcode='"+id_txt.getText()+"'";
        try{
           st=conn.createStatement();
           st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data deleted");
        }catch(Exception j){
            JOptionPane.showMessageDialog(null,"failed deleted "+j);
    }
     Empty_TextField();  
     Upadet_Table();
     Cost();
         Earn();
        }
    }
    }//GEN-LAST:event_delete_purchase_ActionPerformed

    private void profitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profitMouseClicked
        // TODO add your handling code here:
        double remain;
        remain=Double.parseDouble(earn_after_selling.getText())-Double.parseDouble(purcahse_cost.getText());
        profit.setText(""+remain);
    }//GEN-LAST:event_profitMouseClicked

    private void update_purchase_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_purchase_ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
          java.sql.Date date = new java.sql.Date(date_txt.getDate().getTime());
          
            if(id_txt.getText().length()==0 && name_txt.getText().length()==0
               &&selling_txt.getText().length()==0
                && date_txt.getDate().equals("") &&purchase_txt.getText().length()==0
                &&vat_txt.getText().length()==0 &&discount_txt.getText().length()==0
                &&quantity_txt.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Select data from table to update first","Update Information",JOptionPane.INFORMATION_MESSAGE);
        //Empty_TextField();
          return;
        }else{
        try{
        String query_update="update Purchased_Registration set Product_Barcode='"+id_txt.getText()+"',"
                + "Product_Name='"+name_txt.getText()+"',Product_Category='"+(String)category_combo.getSelectedItem()+"',"
                + "Purchase_Price='"+purchase_txt.getText()+"',Vat='"+vat_txt.getText()+"',"
                + "Discount='"+discount_txt.getText()+"',Selling_Price='"+selling_txt.getText()+"',"
                + "Supplier_Name='"+(String)supplier_combo.getSelectedItem()+"',Quantity='"+quantity_txt.getText()+"',Date='"+date+"' where Product_Barcode='"+id_txt.getText()+"'";
            st=conn.createStatement();
            st.executeUpdate(query_update);
              JOptionPane.showMessageDialog(null,"Data updated");
        }catch(Exception c){
          JOptionPane.showMessageDialog(null,"Data failed "+c);
        
        }
        Empty_TextField();
        Upadet_Table();
        Cost();
         Earn();
           }
    }//GEN-LAST:event_update_purchase_ActionPerformed

    private void entry_purchase_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entry_purchase_tableMouseClicked
        // TODO add your handling code here:
          try{
            int row=entry_purchase_table.getSelectedRow();
        String Table_Clicked=(entry_purchase_table.getModel().getValueAt(row, 0).toString());
         String query="select * from Purchased_Registration where Product_Barcode='"+Table_Clicked+"'";
            st= conn.createStatement();
             rs=st.executeQuery(query);
             if(rs.next()){
             id_txt.setText(rs.getString("Product_Barcode"));
              name_txt.setText(rs.getString("Product_Name"));
              //category_combo.addItem(rs.getString("Product_Category"));
              purchase_txt.setText(rs.getString("Purchase_Price"));
              vat_txt.setText(rs.getString("Vat"));
              discount_txt.setText(rs.getString("Discount"));
             selling_txt.setText(rs.getString("Selling_Price"));
             // web_txt.setText(rs.getString("Supplier_Name"));
               quantity_txt.setText(rs.getString("Quantity"));
              date_txt.setDate(rs.getDate("Date"));
             }
        }catch(Exception v){
        
        }
    }//GEN-LAST:event_entry_purchase_tableMouseClicked

    private void entry_purchase_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entry_purchase_tableKeyPressed
        // TODO add your handling code here:
            if(evt.getKeyCode()== KeyEvent.VK_DOWN ||evt.getKeyCode()==KeyEvent.VK_UP ){
        
          try{
            int row=entry_purchase_table.getSelectedRow();
        String Table_Clicked=(entry_purchase_table.getModel().getValueAt(row, 0).toString());
         String query="select * from Purchased_Registration where Product_Barcode='"+Table_Clicked+"'";
            st= conn.createStatement();
             rs=st.executeQuery(query);
             if(rs.next()){
         id_txt.setText(rs.getString("Product_Barcode"));
              name_txt.setText(rs.getString("Product_Name"));
              //category_combo.addItem(rs.getString("Product_Category"));
              purchase_txt.setText(rs.getString("Purchase_Price"));
              vat_txt.setText(rs.getString("Vat"));
              discount_txt.setText(rs.getString("Discount"));
             selling_txt.setText(rs.getString("Selling_Price"));
             // web_txt.setText(rs.getString("Supplier_Name"));
               quantity_txt.setText(rs.getString("Quantity"));
              date_txt.setDate(rs.getDate("Date"));
             
             }
        }catch(Exception v){
        
        
        }
        
        }
    }//GEN-LAST:event_entry_purchase_tableKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_given_topurchase;
    private javax.swing.JTextField balance_after_Paying;
    private javax.swing.JComboBox<String> category_combo;
    private com.toedter.calendar.JDateChooser date_txt;
    private javax.swing.JButton delete_purchase_;
    private javax.swing.JTextField discount_txt;
    private javax.swing.JTextField earn_after_selling;
    private javax.swing.JTable entry_purchase_table;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField profit;
    private javax.swing.JTextField purcahse_cost;
    private javax.swing.JTextField purchase_txt;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JButton save_purchase_;
    private javax.swing.JTextField selling_txt;
    private javax.swing.JComboBox<String> supplier_combo;
    private javax.swing.JButton update_purchase_;
    private javax.swing.JTextField vat_txt;
    private javax.swing.JButton view_purchase_;
    // End of variables declaration//GEN-END:variables
}
