/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Component;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import suppermarket.DatabaseConnection;

/**
 *
 * @author asha
 */
public class Supplier extends javax.swing.JPanel {
     Connection conn;
   Statement st;
   ResultSet rs;
    Statement st1;
   ResultSet rs1;
   DatabaseConnection db;

    /**
     * Creates new form Supplier
     */
    Supplier_order Sorder;
    public Supplier() {
        initComponents();
        Sorder=new Supplier_order();
         db=new DatabaseConnection();
        conn=db.ConnectDB();
    }
         private void Upadet_Table(){
    String query="select * from Supplier_Table ";
    try{
   st= conn.createStatement();
   rs=st.executeQuery(query);
   supplier_table.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(Exception b){
    
    }
    
    }
    
          public void Empty_TextField(){
             id_txt.setText("");
              name_txt.setText("");
              
              address_txt.setText("");
              comp_name_txt.setText("");
              
             mobile_txt.setText("");
             
    
    }
    
   
  private boolean isvalideMobileNumber(String mobile){
       String patern="^[+]\\d{3}-\\d{3}-\\d{6}$";
  
      java.util.regex.Pattern p = java.util.regex.Pattern.compile(patern);
       java.util.regex.Matcher m = p.matcher(mobile);
           return m.matches();
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        save_Supplier = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        clear_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_txt = new javax.swing.JTextArea();
        mobile_txt = new javax.swing.JTextField();
        delet_supplier_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comp_name_txt = new javax.swing.JTextField();
        update_Supplier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        view_supplier_ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        supplier_table = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier > Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suppliers > Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Supplier Name");

        save_Supplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        save_Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Save-icon.png"))); // NOI18N
        save_Supplier.setText("Save");
        save_Supplier.setPreferredSize(new java.awt.Dimension(120, 25));
        save_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_SupplierActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Company Name");

        name_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        clear_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clear_button.setText("Clear");
        clear_button.setPreferredSize(new java.awt.Dimension(120, 25));
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Contact Number");

        address_txt.setColumns(20);
        address_txt.setRows(5);
        jScrollPane1.setViewportView(address_txt);

        mobile_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        delet_supplier_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        delet_supplier_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/Actions-edit-delete-icon.png"))); // NOI18N
        delet_supplier_.setText("Delete");
        delet_supplier_.setPreferredSize(new java.awt.Dimension(120, 25));
        delet_supplier_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_supplier_ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Supplier ID");

        comp_name_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        update_Supplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        update_Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suppermarket/edit-validated-icon.png"))); // NOI18N
        update_Supplier.setText("Update");
        update_Supplier.setPreferredSize(new java.awt.Dimension(120, 25));
        update_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_SupplierActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Supplier Address");

        id_txt.setPreferredSize(new java.awt.Dimension(6, 25));

        view_supplier_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        view_supplier_.setText("View");
        view_supplier_.setPreferredSize(new java.awt.Dimension(120, 25));
        view_supplier_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_supplier_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(delet_supplier_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_supplier_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mobile_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(52, 52, 52))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(id_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(name_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comp_name_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comp_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_supplier_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delet_supplier_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        supplier_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        supplier_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_tableMouseClicked(evt);
            }
        });
        supplier_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supplier_tableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(supplier_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        //Sorder.setVisible(true);
        Empty_TextField();
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void save_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_SupplierActionPerformed
        // TODO add your handling code here:
            if(id_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Supplier ID","ID Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        }else if(name_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Supplier Name","Name Empty",JOptionPane.ERROR_MESSAGE);
        
          return;
        
    
        }else if(address_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Supplier Address","Address Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        
        }else if(comp_name_txt.getText().length()==0){
        JOptionPane.showMessageDialog(null,"Fill Company Name","Email Empty",JOptionPane.ERROR_MESSAGE);
        //Empty_TextField();
       
        }
        
       else if(mobile_txt.getText().length()==0){
        
        JOptionPane.showMessageDialog(null,"Fill Supplier Mobile","Mobile Empty",JOptionPane.ERROR_MESSAGE);
       // Empty_TextField();
          return;
        
        
        
       
        }else
        
        if(isvalideMobileNumber(mobile_txt.getText())== false){
         JOptionPane.showMessageDialog(null,"invalide  Mobile Number","Mobile validate",JOptionPane.ERROR_MESSAGE);
        return;
        
        }else
             
             
            
             {
          
        String sql="insert into Supplier_Table values('"+id_txt.getText()+"',"
                + "'"+name_txt.getText()+"','"+address_txt.getText()+"',"
                + "'"+comp_name_txt.getText()+"','"+mobile_txt.getText()+"')";
        try{
           st=conn.createStatement();
           int p=st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data saved");
        }catch(Exception j){
            JOptionPane.showMessageDialog(null,"failed  saved  "+j);
    }
        
        Empty_TextField();
        Upadet_Table();
        }

    }                                                    

    private void update_custActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
            
    }//GEN-LAST:event_save_SupplierActionPerformed

    private void delet_supplier_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_supplier_ActionPerformed
        // TODO add your handling code here:
                 if(id_txt.getText().length()==0 && name_txt.getText().length()==0
                 &&address_txt.getText().length()==0 && comp_name_txt.getText().length()==0 
                && mobile_txt.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Select data from table to update first","Update Information",JOptionPane.INFORMATION_MESSAGE);
        //Empty_TextField();
          return;
        }else{
                      int p=JOptionPane.showConfirmDialog(null, "Do your really want to delete these data","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
           String sql="delete from Supplier_Table where Supplier_ID='"+id_txt.getText()+"'";
        try{
           st=conn.createStatement();
           st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data deleted");
        }catch(Exception j){
            JOptionPane.showMessageDialog(null,"failed deleted "+j);
    }
     Empty_TextField();  
     Upadet_Table();
        }
                 }
    }//GEN-LAST:event_delet_supplier_ActionPerformed

    private void view_supplier_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_supplier_ActionPerformed
        // TODO add your handling code here:
        Upadet_Table();
    }//GEN-LAST:event_view_supplier_ActionPerformed

    private void supplier_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_tableMouseClicked
        // TODO add your handling code here:
        try{
            int row=supplier_table.getSelectedRow();
        String Table_Clicked=(supplier_table.getModel().getValueAt(row, 0).toString());
         String query="select * from Supplier_Table where Supplier_ID='"+Table_Clicked+"'";
            st= conn.createStatement();
             rs=st.executeQuery(query);
             if(rs.next()){
             id_txt.setText(rs.getString("Supplier_ID"));
              name_txt.setText(rs.getString("Supplier_Name"));
              
              address_txt.setText(rs.getString("Supplier_Address"));
              
              comp_name_txt.setText(rs.getString("Company_Name"));
             mobile_txt.setText(rs.getString("Contant_Number"));
            
               
             
             }
        }catch(Exception v){
        
        }
    }//GEN-LAST:event_supplier_tableMouseClicked

    private void supplier_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplier_tableKeyPressed
        // TODO add your handling code here:
      
          if(evt.getKeyCode()== KeyEvent.VK_DOWN ||evt.getKeyCode()==KeyEvent.VK_UP ){
        
          try{
            int row=supplier_table.getSelectedRow();
        String Table_Clicked=(supplier_table.getModel().getValueAt(row, 0).toString());
         String query="select * from Supplier_Table where Customer_ID='"+Table_Clicked+"'";
            st= conn.createStatement();
             rs=st.executeQuery(query);
             if(rs.next()){
             id_txt.setText(rs.getString("Supplier_ID"));
              name_txt.setText(rs.getString("Supplier_Name"));
             
              address_txt.setText(rs.getString("Supplier_Address"));
              comp_name_txt.setText(rs.getString("Company_Name"));
              mobile_txt.setText(rs.getString("Contant_Number"));
             
             
               //id_txt.setText(rs.getString("Company_Logo"));
             
             }
        }catch(Exception v){
        
        
        }
        
        }
    }//GEN-LAST:event_supplier_tableKeyPressed

    private void update_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_SupplierActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
                 if(id_txt.getText().length()==0 && name_txt.getText().length()==0
                 &&address_txt.getText().length()==0 && comp_name_txt.getText().length()==0 
                && mobile_txt.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Select data from table to update first","Update Information",JOptionPane.INFORMATION_MESSAGE);
        //Empty_TextField();
          return;
        }
        else if(isvalideMobileNumber(mobile_txt.getText())== false){
         JOptionPane.showMessageDialog(null,"invalide  Mobile Number","Mobile validate",JOptionPane.ERROR_MESSAGE);
        return;
        
        }else
             
             
            
             {        
                     
        try{
        String query_update="update Supplier_Table set Supplier_ID='"+id_txt.getText()+"',"
                + "Supplier_Name='"+name_txt.getText()+"',"
                + "Supplier_Address='"+address_txt.getText()+"',"
                + "Company_Name='"+comp_name_txt.getText()+"',"
                + "Contant_Number='"+mobile_txt.getText()+"' where Supplier_ID='"+id_txt.getText()+"'";
            st=conn.createStatement();
            st.executeUpdate(query_update);
              JOptionPane.showMessageDialog(null,"Data updated");
        }catch(Exception c){
          JOptionPane.showMessageDialog(null,"Data failed "+c);
        
        }
        Empty_TextField();
        Upadet_Table();
           }
    }//GEN-LAST:event_update_SupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address_txt;
    private javax.swing.JButton clear_button;
    private javax.swing.JTextField comp_name_txt;
    private javax.swing.JButton delet_supplier_;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton save_Supplier;
    private javax.swing.JTable supplier_table;
    private javax.swing.JButton update_Supplier;
    private javax.swing.JButton view_supplier_;
    // End of variables declaration//GEN-END:variables
}
